### ISSUE TITLE
It´s not a issue

### ISSUE THREAD

**Issue by hugoquintalcr** [khjde1207/tesseract_ocr#1]
I would like to know if I can improve a trained data file to be a better text recognition, ¿Could you tell me if I can?

**Comment by hugoquintalcr** [comment]
*To have

**Comment by khjde1207** [comment]
I do not know.
The ocr recognition rate was improved by correcting the illuminance and gamma of the image.

https://github.com/khjde1207/openTextView/blob/main/lib/controller/MainCtl.dart  315 line 

im.Image image =
              im.decodeImage(File(imgFiles[i].toString()).readAsBytesSync());
          image = im.adjustColor(
            image.clone(),
            gamma: 20,
          );
          File('${imgFiles[i].toString()}_ocr.jpg')
            ..writeAsBytesSync(im.encodeJpg(image));

**Comment by khjde1207** [comment]
The image calibration test used gImageReader.

**Comment by khjde1207** [comment]
https://towardsdatascience.com/simple-ocr-with-tesseract-a4341e4564b6
take a look at this

**Comment by hugoquintalcr** [comment]
Thank you
