### ISSUE TITLE
The build failed likely due to AndroidX incompatibilities in the plugin?

### ISSUE THREAD

**Issue by qodrinzo** [khjde1207/tesseract_ocr#11]
Using **VSCode > Run > Start Debugging**:

> Launching lib\main.dart on SM A305F in profile mode...
> 
> FAILURE: Build failed with an exception.
> 
> * What went wrong:
> Execution failed for task ':app:checkProfileAarMetadata'.
> > Could not resolve all dependencies for configuration ':app:profileRuntimeClasspath'.
>    > Could not determine artifacts for androidx.core:core:1.0.2
>       > Could not get resource 'https://dl.google.com/dl/android/maven2/androidx/core/core/1.0.2/core-1.0.2.aar'.
>          > Could not HEAD 'https://dl.google.com/dl/android/maven2/androidx/core/core/1.0.2/core-1.0.2.aar'.
>             > Connect to localhost:54215 [localhost/127.0.0.1, localhost/0:0:0:0:0:0:0:1] failed: Connection refused: connect
> 
> * Try:
> Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
> 
> * Get more help at https://help.gradle.org
> 
> BUILD FAILED in 5m 34s
> The build failed likely due to AndroidX incompatibilities in a plugin. The tool is about to try using Jetifier to solve the incompatibility.
> Building plugin flutter_plugin_android_lifecycle...
> Exception in thread "main" java.net.ConnectException: Connection refused: connect
> 	at java.base/java.net.PlainSocketImpl.connect0(Native Method)
> 	at java.base/java.net.PlainSocketImpl.socketConnect(PlainSocketImpl.java:101)
> 	at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:399)
> 	at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:242)
> 	at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:224)
> 	at java.base/java.net.Socket.connect(Socket.java:609)
> 	at java.base/java.net.Socket.connect(Socket.java:558)
> 	at java.base/sun.net.NetworkClient.doConnect(NetworkClient.java:182)
> 	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:474)
> 	at java.base/sun.net.www.http.HttpClient$1.run(HttpClient.java:526)
> 	at java.base/sun.net.www.http.HttpClient$1.run(HttpClient.java:524)
> 	at java.base/java.security.AccessController.doPrivileged(Native Method)
> 	at java.base/sun.net.www.http.HttpClient.privilegedOpenServer(HttpClient.java:523)
> 	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:564)
> 	at java.base/sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:265)
> 	at java.base/sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:372)
> 	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:200)
> 	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1208)
> 	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1081)
> 	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177)
> 	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1592)
> 	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1520)
> 	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:250)
> 	at org.gradle.wrapper.Download.downloadInternal(Download.java:58)
> 	at org.gradle.wrapper.Download.download(Download.java:44)
> 	at org.gradle.wrapper.Install$1.call(Install.java:61)
> 	at org.gradle.wrapper.Install$1.call(Install.java:48)
> 	at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:65)
> 	at org.gradle.wrapper.Install.createDist(Install.java:48)
> 	at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:128)
> 	at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)
> Exception: The plugin flutter_plugin_android_lifecycle could not be built due to the issue above.
> Exited (sigterm)
>

**Comment by qodrinzo** [comment]
Seemingly resolved by setting`android.enableJetifier` to `false`, but keeping `android.useAndroidX` as `true`.

**Comment by khjde1207** [comment]
upload your project
Can you tell me how to reproduce it?
