### ISSUE TITLE
Swift Compile Error Unexpected non-void return value in void function

### ISSUE THREAD

**Issue by cansavrun** [khjde1207/tesseract_ocr#16]
I am getting Unexpected non-void return value in void function in SwiftFlutterTesseractOcrPlugin.swift while i try to open the plugin example in ios.

**Comment by khjde1207** [comment]
Can you show all the error messages?

**Comment by cansavrun** [comment]
Thank you for your answer.
This is the error i am getting when i try to write flutter build ios:

```
Xcode's output:
↳
    /Users/cansavrun/development/flutter/.pub-cache/hosted/pub.dartlang.org/image_picker-0.7.5/ios/Classes/FLTImagePickerPlugin.m:193:20: warning: 'UIAlertView' is
    deprecated: first deprecated in iOS 9.0 - UIAlertView is deprecated. Use UIAlertController with a preferredStyle of UIAlertControllerStyleAlert instead
    [-Wdeprecated-declarations]
        [[[UIAlertView alloc] initWithTitle:NSLocalizedString(@"Error", nil)
                       ^
    In module 'UIKit' imported from /Users/cansavrun/Desktop/tesseract_ocr-master/example/ios/Pods/Target Support Files/image_picker/image_picker-prefix.pch:2:
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS14.5.sdk/System/Library/Frameworks/UIKit.framework/Headers/UIAlertView.h:2
    7:12: note: 'UIAlertView' has been explicitly marked deprecated here
    @interface UIAlertView : UIView
               ^
    1 warning generated.
    1 warning generated.
    warning: [CP] Unable to find matching .xcframework slice in 'ios-arm64 ios-x86_64-maccatalyst ios-x86_64-simulator' for the current build architectures (arm64 armv7).
    /Users/cansavrun/Desktop/tesseract_ocr-master/example/ios/Pods/SwiftyTesseract/SwiftyTesseract/SwiftyTesseract/Enums/EngineMode.swift:9:8: error: no such module
    'libtesseract'
    import libtesseract
           ^
    /Users/cansavrun/Desktop/tesseract_ocr-master/example/ios/Pods/SwiftyTesseract/SwiftyTesseract/SwiftyTesseract/Enums/EngineMode.swift:9:8: error: no such module
    'libtesseract'
    import libtesseract
           ^
    note: Using new build system
    note: Building targets in parallel
    note: Planning build
    note: Analyzing workspace
    note: Constructing build description
    note: Build preparation complete

Encountered error while building for device.
```

This is the error while i try to run on xcode:
<img width="259" alt="Ekran Resmi 2021-09-14 20 44 39" src="https://user-images.githubusercontent.com/49312193/133307832-af542a41-54e1-421d-b744-7588c49a1792.png">

This is where i am getting the error on swift:

else if(call.method == "initswiftyTesseract")
        {
            guard let args = call.arguments else {
                result("iOS could not recognize flutter arguments in method: (sendParams)")
                return
            }
            
            let params: [String : Any] = args as! [String : Any]
            let language: String? = params["language"] as? String
            if(language != nil){
                swiftyTesseract = SwiftyTesseract(language: .custom((language as String?)!))
            }
            return true //this part is giving the error
        }

**Comment by khjde1207** [comment]
Please check in the latest version.

**Comment by cansavrun** [comment]
Hi thank you for your response.Sorry for the late response.
I am getting this error now:
2021-09-23 14:40:45.728925+0300 Runner[4879:1452660] Fatal error: Initialization of SwiftyTesseract has failed. Check that the tessdata folder has been added to the project as a folder reference and contains the correct .traineddata files for the specified engine mode and language(s).: file SwiftyTesseract/SwiftyTesseract.swift, line 100

`    else { fatalError(SwiftyTesseract.Error.initializationErrorMessage) }
`

**Comment by khjde1207** [comment]
https://github.com/arrrrny/tesseract_ocr/issues/31
Can you please check if this method solves it?
If it is resolved, can I ask for pull requests?

**Comment by cansavrun** [comment]
It is resolved. But you can add tessdata only in xcode so i think mentioning this solution in readme will be enough.

**Comment by khjde1207** [comment]
good idea.
I'll add it to the readme.

**Comment by ShivamS1234** [comment]
Hi @khjde1207,

I folllow the same steps drag tessdata folder from assets to Xcode Runner folder as a refrence.
still I am getting this error. please help me.

Error Domain=NSCocoaErrorDomain Code=513 "You don’t have permission to save the file “tessdata” in the folder “Gulf Bank”." UserInfo={NSUnderlyingError=0x302b9bcf0 {Error Domain=NSPOSIXErrorDomain Code=1 "Operation not permitted"}, NSFilePath=/private/var/containers/Bundle/Application/4995D7DC-DE6A-4E98-9F80-B90A865EDDD4/Runner.app/tessdata, NSURL=file:///private/var/containers/Bundle/Application/4995D7DC-DE6A-4E98-9F80-B90A865EDDD4/Runner.app/tessdata}
Error opening data file /private/var/containers/Bundle/Application/4995D7DC-DE6A-4E98-9F80-B90A865EDDD4/Runner.app/tessdata/eng.traineddata
Please make sure the TESSDATA_PREFIX environment variable is set to your "tessdata" directory.
Failed loading language 'eng'
Tesseract couldn't load any languages!
SwiftyTesseract/SwiftyTesseract.swift:100: Fatal error: Initialization of SwiftyTesseract has failed. Check that the tessdata folder has been added to the project as a folder reference and contains the correct .traineddata files for the specified engine mode and language(s).

**Comment by cristianlima-bit** [comment]
Hi @ShivamS1234  did you get ? i having the same error :(

**Comment by yuanhoujun** [comment]
@ShivamS1234 Same issue, Any idea?

**Comment by ShivamS1234** [comment]
Dear @yuanhoujun & @cristianlima-bit, Yes I resolved it by added same file reference eng.traineddata inside of the Xcode ---> copy bundle resources then it was resolved.

Thanks.

**Comment by yuanhoujun** [comment]
@ShivamS1234 Got it, resolved too.
