### ISSUE TITLE
iOS Build Error

### ISSUE THREAD

**Issue by batuhankrbb** [khjde1207/tesseract_ocr#17]
Every time I try to run my app on an iOS emulator, I get this error:

Error output from Xcode build:
↳
    ** BUILD FAILED **
Xcode's output:
↳
warning: Stale file '/Users/batuhankarababa/iban-flutter-1/build/ios/Debug-iphonesimulator/flutter_tesseract_ocr/flutter_tesseract_ocr.framework/Modules/flutter_tesseract_ocr.swiftmodule/arm64-apple-ios-simulator.swiftinterface' is located outside of the allowed root paths.
    warning: Stale file '/Users/batuhankarababa/iban-flutter-1/build/ios/Debug-iphonesimulator/flutter_tesseract_ocr/flutter_tesseract_ocr.framework/Modules/flutter_tesseract_ocr.swiftmodule/arm64.swiftinterface' is located outside of the allowed root paths.
    warning: Stale file '/Users/batuhankarababa/iban-flutter-1/build/ios/Debug-iphonesimulator/flutter_tesseract_ocr/flutter_tesseract_ocr.framework/Modules/flutter_tesseract_ocr.swiftmodule/x86_64-apple-ios-simulator.swiftinterface' is located outside of the allowed root paths.
    warning: Stale file '/Users/batuhankarababa/iban-flutter-1/build/ios/Debug-iphonesimulator/flutter_tesseract_ocr/flutter_tesseract_ocr.framework/Modules/flutter_tesseract_ocr.swiftmodule/x86_64.swiftinterface' is located outside of the allowed root paths.
    Command CompileSwift failed with a nonzero exit code
    /Users/batuhankarababa/Developer/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_tesseract_ocr-0.4.14/ios/Classes/SwiftFlutterTesseractOcrPlugin.swift:3:8: error: could not find module 'SwiftyTesseract' for target 'arm64-apple-ios-simulator'; found: x86_64-apple-ios-simulator, x86_64
    import SwiftyTesseract
           ^
    note: Using new build system
    note: Building targets in parallel
    note: Planning build
    note: Constructing build description

**Comment by khjde1207** [comment]
I don't have a Mac machine so I can't test it.
I'm sorry.

**Comment by batuhankrbb** [comment]
hey! Yes that method has solved it. It didn't solve at first since I try to move folders on vscode. We should move folders on Xcode
