### ISSUE TITLE
.aar file dependencies are not supported when building an AAR.

### ISSUE THREAD

**Issue by Wasimshaikh99** [khjde1207/tesseract_ocr#2]
* What went wrong:
Execution failed for task ':tesseract_ocr:bundleDebugAar'.
> Direct local .aar file dependencies are not supported when building an AAR. The resulting AAR would be broken because the classes and Android resources from any local .aar file dependencies would not be packaged in the resulting AAR. Previous versions of the Android Gradle Plugin produce broken AARs in this case too (despite not throwing this error). The following direct local .aar file dependencies of the :tesseract_ocr project caused this error: C:\src\flutter\flutter\.pub-cache\hosted\pub.dartlang.org\tesseract_ocr-0.3.1\android\libs\tesseract4android-release.aar

**Comment by khjde1207** [comment]
check ./android/build.gradle : 9 line 
classpath 'com.android.tools.build:gradle:3.6.2'

./android/app/build.gradle 
 packagingOptions{
      doNotStrip '*/mips/*.so'
      doNotStrip '*/mips64/*.so'
    }

**Comment by khjde1207** [comment]
I found a way.
Please use version 0.3.7.
