### ISSUE TITLE
Extract text based on bytes buffer insead of file path

### ISSUE THREAD

**Issue by mspnr** [khjde1207/tesseract_ocr#20]
Could you consider to add a new `extractText` function?

# Suggestion for improvement

As you already mentioned in #9 if you transfer data directly from camera or somehow manipulate images (changing contrast, cropping etc.), it makes sense to transfer to [`extractText`](https://github.com/khjde1207/tesseract_ocr/blob/93e74d3694a7351eca70ce997e235404aa046ddb/lib/android_ios.dart#L22) byte buffer instead of a file path, Otherwise you need to resave the image, which can lead to exceeding use of flash drive.

# Technical considerations

## Android

From Android side it looks like instead of calling [`this.baseApi.setImage(this.tempFile);`](https://github.com/khjde1207/tesseract_ocr/blob/93e74d3694a7351eca70ce997e235404aa046ddb/android/src/main/java/io/paratoner/flutter_tesseract_ocr/FlutterTesseractOcrPlugin.java#L104) with passing a file path one can use another [`public void setImage(Bitmap bmp)`](https://github.com/adaptech-cz/Tesseract4Android/blob/08994a82e108bd179e29993a4b2ceb143bd0a932/tesseract4android/src/main/java/com/googlecode/tesseract/android/TessBaseAPI.java#L646) for passing a bitmap.

## iOS

From iOS side it looks like also feasible instead of calling [`let image = UIImage(contentsOfFile: imagePath)`](https://github.com/khjde1207/tesseract_ocr/blob/93e74d3694a7351eca70ce997e235404aa046ddb/ios/Classes/SwiftFlutterTesseractOcrPlugin.swift#L28) one can use another constructor of `UIImage`: [`init?(data: Data)`](https://developer.apple.com/documentation/uikit/uiimage/1624106-init).

# Alternative solution

As a quick alternative solution one can consider to use `MemoryFileSystem()` from [file](https://pub.dev/packages/file) package. In this case it will be enough if `extractText` accepts `File` instead of a path.

**Comment by khjde1207** [comment]
Consider using google_ml_kit
I'm going to use google_ml_kit now.

**Comment by mohblnk** [comment]
> Consider using google_ml_kit I'm going to use google_ml_kit now.

I want to use that option as well but I have custom train data, is there is a way to use custom train data for google_ml_kit?

**Comment by khjde1207** [comment]
> > Consider using google_ml_kit I'm going to use google_ml_kit now.
> 
> I want to use that option as well but I have custom train data, is there is a way to use custom train data for google_ml_kit?

Custom doesn't seem to be supported.
