### ISSUE TITLE
White text recognition problem

### ISSUE THREAD

**Issue by Niravoo7** [khjde1207/tesseract_ocr#23]
In this plugin white text on image is note recognise.
![Screenshot 2021-12-29 at 12 39 52 PM](https://user-images.githubusercontent.com/32232529/147636332-a504418b-b2f3-4993-8430-a30d1950ee8c.png)
.

**Comment by khjde1207** [comment]
This is a tesseract problem.
Check it out with GimageReader. 
![스크린샷, 2022-01-01 01-19-39](https://user-images.githubusercontent.com/18232924/147832200-1f619a9d-857b-4463-abcc-51778bf72e9a.png)
