### ISSUE TITLE
CocoaPods could not find compatible versions for pod "flutter_tesseract_ocr":

### ISSUE THREAD

**Issue by tonyteo72** [khjde1207/tesseract_ocr#27]
I tried to build my app for ios and got the following error. Kindly advice how to resolve.

[!] CocoaPods could not find compatible versions for pod "flutter_tesseract_ocr":
  In Podfile:
    flutter_tesseract_ocr (from `.symlinks/plugins/flutter_tesseract_ocr/ios`)

Specs satisfying the `flutter_tesseract_ocr (from `.symlinks/plugins/flutter_tesseract_ocr/ios`)` dependency were found, but they required a higher minimum deployment target.

**Comment by danielmessi13** [comment]
I have the same problem!

**Comment by rocassis** [comment]
Try update the file: <your_project>/ios/.symlinks/plugins/flutter_tesseract_ocr/ios/flutter_tesseract_ocr.podspec
And then run pod update

`#
# To learn more about a Podspec see http://guides.cocoapods.org/syntax/podspec.html
#
Pod::Spec.new do |s|
  s.name             = 'flutter_tesseract_ocr'
  s.version          = '0.3.4'
  s.summary          = 'Tesseract OCR 4 Flutter'
  s.description      = <<-DESC
Tesseract 4 adds a new neural net (LSTM) based OCR engine which is focused on line recognition. It has unicode (UTF-8) support, and can recognize more than 100 languages.
                       DESC
  s.homepage         = 'https://paratoner.io'
  s.license          = { :file => '../LICENSE',:type => 'BSD' }
  s.author           = { 'Ahmet Tok' => 'arny@paratoner.io' }
  s.source           = { :path => '.' }
  s.source_files = 'Classes/**/*'
  s.public_header_files = 'Classes/**/*.h'
  s.dependency 'Flutter'
  s.dependency 'SwiftyTesseract'
  s.platform = :ios, '11.0'
  s.pod_target_xcconfig = { 'DEFINES_MODULE' => 'YES' }
end`

**Comment by rocassis** [comment]
> I tried to build my app for ios and got the following error. Kindly advice how to resolve.
> 
> [!] CocoaPods could not find compatible versions for pod "flutter_tesseract_ocr": In Podfile: flutter_tesseract_ocr (from `.symlinks/plugins/flutter_tesseract_ocr/ios`)
> 
> Specs satisfying the `flutter_tesseract_ocr (from `.symlinks/plugins/flutter_tesseract_ocr/ios`)` dependency were found, but they required a higher minimum deployment target.

Update you file:  <your-project>/ios/.symlinks/plugins/flutter_tesseract_ocr/ios/flutter_tesseract_ocr.podspec
And them run: `pod update`

#
# To learn more about a Podspec see http://guides.cocoapods.org/syntax/podspec.html
#
Pod::Spec.new do |s|
  s.name             = 'flutter_tesseract_ocr'
  s.version          = '0.3.4'
  s.summary          = 'Tesseract OCR 4 Flutter'
  s.description      = <<-DESC
Tesseract 4 adds a new neural net (LSTM) based OCR engine which is focused on line recognition. It has unicode (UTF-8) support, and can recognize more than 100 languages.
                       DESC
  s.homepage         = 'https://paratoner.io'
  s.license          = { :file => '../LICENSE',:type => 'BSD' }
  s.author           = { 'Ahmet Tok' => 'arny@paratoner.io' }
  s.source           = { :path => '.' }
  s.source_files = 'Classes/**/*'
  s.public_header_files = 'Classes/**/*.h'
  s.dependency 'Flutter'
  s.dependency 'SwiftyTesseract'
  s.platform = :ios, '11.0'
  # s.ios.deployment_target = '12.0'
  # s.swift_version = '5.0'
  s.pod_target_xcconfig = { 'DEFINES_MODULE' => 'YES' }
  # s.pod_target_xcconfig = { 'SWIFT_VERSION' => '5.0' }
end

**Comment by khjde1207** [comment]
thank you.
It's corrected.
