### ISSUE TITLE
Not an issue, but a question

### ISSUE THREAD

**Issue by KiranThomasCherian** [khjde1207/tesseract_ocr#3]
What change should be made to make use of this on flutter web .Is it possible? (Without storing the image locally)

**Comment by khjde1207** [comment]
The web doesn't support yet.
https://www.npmjs.com/package/tesseract.js/v/2.1.1
I think it can be implemented with tesseract.js.
I don't know if I can do this.
I'll try when I have time.

**Comment by khjde1207** [comment]
I have confirmed that ocr works on the web.
We will try to complete the development within this week.

**Comment by KiranThomasCherian** [comment]
Ok, Thank you
