### ISSUE TITLE
 i want specific text from a given image

### ISSUE THREAD

**Issue by iusamaashraf** [khjde1207/tesseract_ocr#31]
Hello!
sir i have implemented your package and it's working well but i have faced some difficulty to extract specific text from image like i scan a ID Card and i want only first name and last name from that then how is this possible?

**Comment by khjde1207** [comment]
If the location is fixed, it seems to be a way to cut and recognize ocr.

**Comment by iusamaashraf** [comment]
> If the location is fixed, it seems to be a way to cut and recognize ocr.

sorry i didn't understand can you elaborate this little bit more?

**Comment by khjde1207** [comment]
https://github.com/brendan-duncan/image/blob/main/doc/transform.md

If the name and location are always the same on the id card, why not cut the name part?
