### ISSUE TITLE
识别手写的内容，返回都为空

### ISSUE THREAD

**Issue by lurongshuang** [khjde1207/tesseract_ocr#38]
FlutterTesseractOcr.extractText  
![image](https://github.com/khjde1207/tesseract_ocr/assets/20178753/1618f4c6-649c-487f-96d7-b208d743d672)

**Comment by khjde1207** [comment]
https://github.com/tesseract-ocr/tesseract
Just use PC Tesseract to check.

**Comment by lurongshuang** [comment]
> https://github.com/tesseract-ocr/tesseract 只需使用PC Tesseract即可检查。
您好 是运行在手机上的结果，使用的版本是 flutter_tesseract_ocr 0.4.23

**Comment by khjde1207** [comment]
This library was created for use in flutter.
https://github.com/adaptech-cz/Tesseract4Android/
It cannot solve Tesseract problems or Tesseract4Android problems.
