### ISSUE TITLE
Persist TessBaseAPI over calls for better performance

### ISSUE THREAD

**Issue by TheLastGimbus** [khjde1207/tesseract_ocr#4]
Hi there!
I see that, out of tens of `tesseract_ocr` forks, this one seems most maintained - thank you!

I don't know what are your plans, but core feature of my app is ocr, so I'm very interested in helping you to maintain this!

Okay, countresy aside - I see that the `TessBaseAPI` object is re-initiated *every* call:

https://github.com/khjde1207/tesseract_ocr/blob/934300d2cdf321a2182195c917cb219267f56e10/android/src/main/java/io/paratoner/flutter_tesseract_ocr/FlutterTesseractOcrPlugin.java#L45

Isn't this inafficient? Can we persist it somewhere and expose methods to init/dispose it?

**Comment by khjde1207** [comment]
Good idea.
It's currently being developed for web support.
I'll check it out when the web support development is done.

**Comment by khjde1207** [comment]
0.2 seconds faster per page than before 
I tested it with 10 pages.
About 2 seconds faster.

**Comment by TheLastGimbus** [comment]
This is great! Thanks!!
